### PR TITLE
Replace CircleCI with GitHub actions

### PR DESCRIPTION
**Pull request by mijicd**
As mentioned in the PR title, I have replaced CircleCI with GitHub actions. However, I noticed a few things in the old CI setup:

- some jobs weren't used (e.g. dotty builds, jmh cross-compilation)
- scala versions weren't compatible with BuildHelper
- JS isn't tested (well, all tests are JVM specific atm)
- Dotty doesn't seem to be working

Please make sure to keep the CI setup tidy and up to date and let me or @softinio know if you need any help.

### CODE REVIEW

**Comment by fsvehla** [comment]
@mijicd Those have been on purpose:

- Some jobs weren't used (e.g. dotty builds, jmh cross-compilation)
- JS isn't tested (well, all tests are JVM specific atm)
- Dotty doesn't seem to be working

What do we need to get this over the finishing line?

**Comment by mijicd** [comment]
Well, i have ported the working jmh steps and added the test/compile js step in. Dotty is failing. It's up to you guys to make that one happening.

My goal with this PR is to move away from CircleCI as we're doing that across the org.

**Comment by fsvehla** [comment]
If we can disable the same steps that were disabled with CircleCI we can move right away.

**Comment by fsvehla** [comment]
@mijicd To expand, Dotty and Magnolia is not trivial. It has not worked so far, which is why the steps were disabled.

**Comment by mijicd** [comment]
Yeah, the current setup contains only the passing steps from CircleCI plus the js step :).

That's what i meant with Dotty: once you have it up and running, please add it to actions.

**Comment by fsvehla** [comment]
Understood!

**Pull request merged**
