### PR TITLE
Fixes #132:  throws AOOBE

### LINKED ISSUE #132: `orElse` decoder combinator throws IndexOutOfBound exception
A soos as someone try to use `JsonDecoder.orElse`, we get that stack trace: 

```
java.lang.ArrayIndexOutOfBoundsException: 0
	at zio.json.internal.WithRecordingReader.readChar(readers.scala:185)
	at zio.json.internal.OneCharReader.nextNonWhitespace(readers.scala:32)
	at zio.json.internal.OneCharReader.nextNonWhitespace$(readers.scala:30)
	at zio.json.internal.WithRecordingReader.nextNonWhitespace(readers.scala:158)
	at zio.json.internal.Lexer$.char(lexer.scala:283)
	at zio.json.internal.Lexer$.string(lexer.scala:140)
	at zio.json.JsonDecoder$$anon$4.unsafeDecode(decoder.scala:303)
	at zio.json.JsonDecoder$$anon$4.unsafeDecode(decoder.scala:301)
	at zio.json.JsonDecoder$$anon$2.unsafeDecode(decoder.scala:217)
	at zio.json.JsonDecoder$$anon$1.unsafeDecode(decoder.scala:191)
	at zio.json.JsonDecoder.decodeJson(decoder.scala:51)
	at zio.json.JsonDecoder.decodeJson$(decoder.scala:50)
	at zio.json.JsonDecoder$$anon$1.decodeJson(decoder.scala:187)
	at zio.json.package$DecoderOps$.fromJson$extension(package.scala:23)
```

The cause is that `orElse` use `WithRecordingReader` with an initial value of 0.

### PR DESCRIPTION
**Pull request by fanf**
Change bad value of `0` for `intial` parameter of `WithRecordingReader`.
Add an argument check in `WithRecordingReader` to avoid that error in the future. 
Add a test case for `orElse` combinator - I'm not sure how to use it without `asInstanceOf[]` given variance and inference in each part, which doesn't seems to be a good practice.
Add a comment in `orElse` to explain that it can be unsafe regarding DOS attack, and show an hand-coded alternative in comment.
Add tests.

### CODE REVIEW

**Comment by fsvehla** [comment]
@fanf Can you run `fmt` on your code?

**Comment by fanf** [comment]
done

**Comment by jdegoes** [comment]
@fanf Can you merge latest and run `scalafmt` on build, test, and src, and then we're good to merge?

**Comment by fanf** [comment]
@jdegoes "merge latest": do you want me to rebase in one commit? Or just rebase on master head? Or do you prefer a merge commit?
(I'm not sure what is the general rule about that, the contributor doc (https://zio.github.io/zio-json/docs/about/about_contributing) does not seems to deal with that point even if it talks about the last of the three options - so maybe merge commit?)

**Comment by fsvehla** [comment]
@fanf Can you run Scalafix as well?

**Comment by fsvehla** [comment]
Thanks!

**Pull request merged**
