### PR TITLE
Upgrade to ZIO 2.0.0-M4

### LINKED ISSUE #463: Upgrade to ZIO 2
ZIO is at Milestone 4, with an RC expected in the next few weeks.
https://github.com/zio/zio/releases/tag/v2.0.0-M4

The API is nearly stable at this point, so any early migration work against this version should pay off towards the official 2.0 release.

The progress is being tracked here:
https://github.com/zio/zio/issues/5470

The Stream Encoding work in progress is the only area where the API might still change before the RC.

To assist with the migration, follow this guide:
https://zio.dev/howto/migrate/zio-2.x-migration-guide/

We are actively working on a ScalaFix rule that will cover the bulk of the simple API changes:
https://github.com/zio/zio/blob/series/2.x/scalafix/rules/src/main/scala/fix/Zio2Upgrade.scala

### PR DESCRIPTION
**Pull request by swoogles**
Potentially fixes #463
Mainly want to run the CI process against this branch, as I'm seeing some cross version errors locally.

### CODE REVIEW

**Comment by fsvehla** [comment]
We need to figure out how to support ZIO 1 and 2, we could start with a topic branch and publish snapshots from there, wdyt?

**Comment by swoogles** [comment]
Ah, I see. Are you available to discuss the details of what needs to happen
via Slack/Zoom/etc? @fsvehla

**Comment by swoogles** [comment]
I think this is as far as this branch can get, until zio-interop-cats is migrated to ZIO 2.
They already have ZIO 2 M2 branch, so I will work on getting them up to M4.

**Comment by swoogles** [comment]
Aware of the failures. I'll address them shortly!

**Pull request closed without merging**
