### PR TITLE
Allow Scala 3 for Refined

### LINKED ISSUE #571: Interop Modules not published for Scala 3
I'm migrating an existing project from cats and scala 2 to zio 2 and scala 3. The interop modules especially the refined module are not available for scala 3. Because of this I can't even start my build as sbt complains about cross compilation problems.

What is the reason for the interop modules not being published for scala 3?

### PR DESCRIPTION
**Pull request by longliveenduro**
Fixes https://github.com/zio/zio-json/issues/571

Works for me with Scala 3

### CODE REVIEW

**Comment by OlegEfrem** [comment]
@fsvehla @plokhotnyuk any chance guys you could approve/merge this PR? 
We're on scala 3 and would love to use refined with zio-json.

**Comment by OlegEfrem** [comment]
wow, that was fast, thanks a lot @jdegoes

**Comment by wadouk** [comment]
Imagine that until release, using snapshot version should be the same ?

**Comment by OlegEfrem** [comment]
@wadouk if there was a question whether it can be used until release, you can just add sonatype snapshots repo: 
`resolvers ++= Seq("public", "snapshots", "releases").flatMap(Resolver.sonatypeOssRepos)`
then add snapshot dependency: 
`libraryDependencies ++=Seq("dev.zio" %% "zio-json-interop-refined"     % "0.3.0+22-42cc4e4d-SNAPSHOT")`

**Comment by wadouk** [comment]
I had add 
`oss-sonatype-snapshots: https://oss.sonatype.org/content/repositories/snapshots/` in `repositories.txt` but it was not enough
By adding to `build.sbt` it's OK in sbt but not in intellij. I add to `repositories.txt`
```
oss-sonatype-snapshots: https://s01.oss.sonatype.org/content/repositories/snapshots/
oss-sonatype-public: https://s01.oss.sonatype.org/content/repositories/public/
oss-sonatype-releases: https://s01.oss.sonatype.org/content/repositories/releases/
```
doesn't understand how it works in sbt because don't find the `_3` in different urls ... it seem to work, so great.

And I set `scalaVersion := "3.2.0"` version  `"3.0.2"` give incompatible bytecode

and now I have compilation errors

**Comment by OlegEfrem** [comment]
I have repos in my build.sbt, with these versions it is working for me: 
java: 17.0.5-tem
sbt: 1.7.3
scala: 3.2.0

You need to have these both in IntelliJ (if running from there) and in your local machine (for this i used sdkman).

**Pull request merged**
