### PR TITLE
fix(num): preserve num-types in ast

### PR DESCRIPTION
**Pull request by ThijsBroersen**
Attempt to fix issue #746

### CODE REVIEW

**Comment by plokhotnyuk** [comment]
@ThijsBroersen Could you please remove `.toDouble` from the implementation of `Num.apply(value: Float)`?

**Comment by ThijsBroersen** [comment]
@plokhotnyuk 

Can this PR merge?

**Comment by plokhotnyuk** [comment]
Yes, I would merge it, but unfortunately, have no rights for that.

**Comment by ThijsBroersen** [comment]
@fsvehla are you able to give this a nudge?

**Comment by fsvehla** [comment]
Thanks for your work on this.

**Pull request merged**
