### PR TITLE
annotation to hide case class field from encoder #253

### PR DESCRIPTION
**Pull request by jgoday**
Define jsonExcludeFields annotation to exclude fields from the encoding JSON.
Added "exclude fields" test case.

`final case class jsonExcludeFields(fields: List[String]) extends Annotation`

### CODE REVIEW

**Comment by fsvehla** [comment]
@jgoday Could this annotation also be added on the fields? I’m conflicted about the correct approach — just wondering.

**Comment by jgoday** [comment]
> 
> 
> @jgoday Could this annotation also be added on the fields? I’m conflicted about the correct approach — just wondering.

@fsvehla Just updated PR to allow @jsonExclude annotation directly on case class field.
Don't know if both annotations (jsonExcludeFields and jsonExclude) makes sense ? or maybe, it's better to create a more general one and make it work in both cases ...

**Comment by fsvehla** [comment]
@jgoday I think the annotation on the field is sufficient. Please run `prepare` in SBT to fix the lint errors.

**Comment by jgoday** [comment]
> @jgoday I think the annotation on the field is sufficient. Please run `prepare` in SBT to fix the lint errors.

@fsvehla Just removed jsonexcludefields and keep only jsonexclude (as a field annotation). I have executed 'prepare'  too. :+1:

**Comment by fsvehla** [comment]
Thanks of your work on this, @jgoday!

**Pull request merged**
